### ISSUE TITLE
Investigate how to integrate CI/CD with github actions

### ISSUE THREAD

**Issue by adriancast** [adriancast/django-template#10]
would be nice to give a built-in CI/CD integration with Github actions. Things to check:
- How to build docker images and publish them to a repository like  docker hub.
- Check how to control the deployment with this images. Not sure if the docker-compose image file should be pinned or should do something like download the latest image available on the docker image repository

**Comment by Myugen** [comment]
Hello, if nobody is working on this, I can take it :smiley:

**Comment by adriancast** [comment]
I would like to add Jose to the conversation, today we finished some investigation of how this should be implemented this issue.

The key points are:
- Use Github actions
- Use DockerHub to host the Docker images

The process will consist of the following phases:

1. We should add Github actions to the generated projects.
2.  The GitHub action should build the web service and push it to DockerHub.
3.  Once pushed it should execute a command to deploy the app in the production server. We could add a deploy.sh command that restarts that pulls the latest image and restarts the server. This file should be added in the root of the generated project.


How the execute a script in the production server using Github actions: [Link](https://hoohoo.top/blog/20210525232300-github-action-auto-ssh-to-host-and-excute-script/)

How to update and restart the production web service in the production server: [Link](https://stackoverflow.com/questions/49316462/how-to-update-existing-images-with-docker-compose)

**Comment by sanmojose** [comment]
Yeah, let me have a try!

**Comment by adriancast** [comment]
Hello @sanmojose,

Your changes are already merged. This feature is live! 🎉🎉🎉🎉🎉🎉🎉

Thanks all for the support in this project!

Regards,
Adrián.
