### ISSUE TITLE
Improve usage documentation

### ISSUE THREAD

**Issue by adriancast** [adriancast/django-template#11]
With the use of the template, I am sure that there are some minor details that would be nice if they are added in the README. By default, this template creates a README for the project, would be nice to add those tricks in that file

**Comment by AcousticCh** [comment]
all of my experience with APIs so far is in flask but i would recommend adding some info that help newer developers learn info that can be hard to find like "You should always escape client side input as a hacker might attempt to use a script injection technique this will prevent any js script they injected through html <script> tags"

**Comment by adriancast** [comment]
Hello @AcousticCh that would be cool but not sure if should be added in the README of the generated projects or in the documentation. Could you elaborate on a few more ideas? Maybe if we have a few core pieces of advice we could add them to the generated project README file.
