### ISSUE TITLE
Fetures Brainstorming

### ISSUE THREAD

**Issue by adriancast** [adriancast/django-template#12]
If you have any cool idea you would like to have in this template, please wrote a response to this issue.

Happy hacking!

**Comment by jairoufps** [comment]
Hello, i think i could change  these images of the docs for an architectural image in the style how to work

![Screenshot - 2021-10-04T232501 176](https://user-images.githubusercontent.com/23509868/135960057-614a39fc-61b2-4420-8224-f938017cbf9d.png)

**Comment by adriancast** [comment]
Hello @jairoufps, the readme is a little shabby, to be honest. Feel free to create a PR with an improvement of the images. In addition, would be awesome if you create an issue in this repository to keep track of this task.

Regards,
Adrián.
