### ISSUE TITLE
Add .idea to gitignore

### ISSUE THREAD

**Issue by adriancast** [adriancast/django-template#2]

**Comment by Anu9518** [comment]
Hi Adriancast,

I would like to work on this.

**Comment by Anu9518** [comment]
Hi Adriancast,

.idea is already added in gitignore, do you want to add anything more?

**Comment by adriancast** [comment]
Hello @Anu9518 the .gitignore that is used when the project is built with this template is this: https://github.com/adriancast/django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.gitignore

Would be cool to have a generic .gitignore with .IDEA , *.pyc etc. Feel free to add whatever you like.

Regards,
Adrián.
